//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ProjectSourceDb", "FK_Event_To_Feed", "ProjectSource", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InnerTrack.Processes.ProjectSource), "ProjectSourceEntry", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InnerTrack.Processes.ProjectSourceEntry), true)]
[assembly: EdmRelationshipAttribute("ProjectSourceDb", "FK_ProjectSource_To_ProjectSourceType", "ProjectSourceType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InnerTrack.Processes.ProjectSourceType), "ProjectSource", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InnerTrack.Processes.ProjectSource), true)]

#endregion

namespace InnerTrack.Processes
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ProjectSourceDbContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ProjectSourceDbContainer object using the connection string found in the 'ProjectSourceDbContainer' section of the application configuration file.
        /// </summary>
        public ProjectSourceDbContainer() : base("name=ProjectSourceDbContainer", "ProjectSourceDbContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ProjectSourceDbContainer object.
        /// </summary>
        public ProjectSourceDbContainer(string connectionString) : base(connectionString, "ProjectSourceDbContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ProjectSourceDbContainer object.
        /// </summary>
        public ProjectSourceDbContainer(EntityConnection connection) : base(connection, "ProjectSourceDbContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProjectSource> ProjectSources
        {
            get
            {
                if ((_ProjectSources == null))
                {
                    _ProjectSources = base.CreateObjectSet<ProjectSource>("ProjectSources");
                }
                return _ProjectSources;
            }
        }
        private ObjectSet<ProjectSource> _ProjectSources;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProjectSourceEntry> ProjectSourceEntries
        {
            get
            {
                if ((_ProjectSourceEntries == null))
                {
                    _ProjectSourceEntries = base.CreateObjectSet<ProjectSourceEntry>("ProjectSourceEntries");
                }
                return _ProjectSourceEntries;
            }
        }
        private ObjectSet<ProjectSourceEntry> _ProjectSourceEntries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProjectSourceType> ProjectSourceTypes
        {
            get
            {
                if ((_ProjectSourceTypes == null))
                {
                    _ProjectSourceTypes = base.CreateObjectSet<ProjectSourceType>("ProjectSourceTypes");
                }
                return _ProjectSourceTypes;
            }
        }
        private ObjectSet<ProjectSourceType> _ProjectSourceTypes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProjectSources EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProjectSources(ProjectSource projectSource)
        {
            base.AddObject("ProjectSources", projectSource);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProjectSourceEntries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProjectSourceEntries(ProjectSourceEntry projectSourceEntry)
        {
            base.AddObject("ProjectSourceEntries", projectSourceEntry);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProjectSourceTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProjectSourceTypes(ProjectSourceType projectSourceType)
        {
            base.AddObject("ProjectSourceTypes", projectSourceType);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectSourceDb", Name="ProjectSource")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProjectSource : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProjectSource object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="projectSourceTypeId">Initial value of the ProjectSourceTypeId property.</param>
        /// <param name="createdBy">Initial value of the CreatedBy property.</param>
        /// <param name="createdOn">Initial value of the CreatedOn property.</param>
        public static ProjectSource CreateProjectSource(global::System.Int32 id, global::System.Int32 projectSourceTypeId, global::System.String createdBy, global::System.DateTime createdOn)
        {
            ProjectSource projectSource = new ProjectSource();
            projectSource.Id = id;
            projectSource.ProjectSourceTypeId = projectSourceTypeId;
            projectSource.CreatedBy = createdBy;
            projectSource.CreatedOn = createdOn;
            return projectSource;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProjectSourceTypeId
        {
            get
            {
                return _ProjectSourceTypeId;
            }
            set
            {
                OnProjectSourceTypeIdChanging(value);
                ReportPropertyChanging("ProjectSourceTypeId");
                _ProjectSourceTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProjectSourceTypeId");
                OnProjectSourceTypeIdChanged();
            }
        }
        private global::System.Int32 _ProjectSourceTypeId;
        partial void OnProjectSourceTypeIdChanging(global::System.Int32 value);
        partial void OnProjectSourceTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Configuration
        {
            get
            {
                return _Configuration;
            }
            set
            {
                OnConfigurationChanging(value);
                ReportPropertyChanging("Configuration");
                _Configuration = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Configuration");
                OnConfigurationChanged();
            }
        }
        private global::System.String _Configuration;
        partial void OnConfigurationChanging(global::System.String value);
        partial void OnConfigurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private global::System.DateTime _CreatedOn;
        partial void OnCreatedOnChanging(global::System.DateTime value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private global::System.String _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.String value);
        partial void OnUpdatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdatedOn
        {
            get
            {
                return _UpdatedOn;
            }
            set
            {
                OnUpdatedOnChanging(value);
                ReportPropertyChanging("UpdatedOn");
                _UpdatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedOn");
                OnUpdatedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdatedOn;
        partial void OnUpdatedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdatedOnChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjectSourceDb", "FK_Event_To_Feed", "ProjectSourceEntry")]
        public EntityCollection<ProjectSourceEntry> ProjectSourceEntries
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ProjectSourceEntry>("ProjectSourceDb.FK_Event_To_Feed", "ProjectSourceEntry");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ProjectSourceEntry>("ProjectSourceDb.FK_Event_To_Feed", "ProjectSourceEntry", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjectSourceDb", "FK_ProjectSource_To_ProjectSourceType", "ProjectSourceType")]
        public ProjectSourceType ProjectSourceType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProjectSourceType>("ProjectSourceDb.FK_ProjectSource_To_ProjectSourceType", "ProjectSourceType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProjectSourceType>("ProjectSourceDb.FK_ProjectSource_To_ProjectSourceType", "ProjectSourceType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ProjectSourceType> ProjectSourceTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProjectSourceType>("ProjectSourceDb.FK_ProjectSource_To_ProjectSourceType", "ProjectSourceType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ProjectSourceType>("ProjectSourceDb.FK_ProjectSource_To_ProjectSourceType", "ProjectSourceType", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectSourceDb", Name="ProjectSourceEntry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProjectSourceEntry : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProjectSourceEntry object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="projectSourceId">Initial value of the ProjectSourceId property.</param>
        /// <param name="sourceEntryId">Initial value of the SourceEntryId property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="createdBy">Initial value of the CreatedBy property.</param>
        /// <param name="createdOn">Initial value of the CreatedOn property.</param>
        public static ProjectSourceEntry CreateProjectSourceEntry(global::System.Int32 id, global::System.Int32 projectSourceId, global::System.Int32 sourceEntryId, global::System.String title, global::System.String createdBy, global::System.DateTime createdOn)
        {
            ProjectSourceEntry projectSourceEntry = new ProjectSourceEntry();
            projectSourceEntry.Id = id;
            projectSourceEntry.ProjectSourceId = projectSourceId;
            projectSourceEntry.SourceEntryId = sourceEntryId;
            projectSourceEntry.Title = title;
            projectSourceEntry.CreatedBy = createdBy;
            projectSourceEntry.CreatedOn = createdOn;
            return projectSourceEntry;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProjectSourceId
        {
            get
            {
                return _ProjectSourceId;
            }
            set
            {
                OnProjectSourceIdChanging(value);
                ReportPropertyChanging("ProjectSourceId");
                _ProjectSourceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProjectSourceId");
                OnProjectSourceIdChanged();
            }
        }
        private global::System.Int32 _ProjectSourceId;
        partial void OnProjectSourceIdChanging(global::System.Int32 value);
        partial void OnProjectSourceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SourceEntryId
        {
            get
            {
                return _SourceEntryId;
            }
            set
            {
                OnSourceEntryIdChanging(value);
                ReportPropertyChanging("SourceEntryId");
                _SourceEntryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SourceEntryId");
                OnSourceEntryIdChanged();
            }
        }
        private global::System.Int32 _SourceEntryId;
        partial void OnSourceEntryIdChanging(global::System.Int32 value);
        partial void OnSourceEntryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private global::System.DateTime _CreatedOn;
        partial void OnCreatedOnChanging(global::System.DateTime value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private global::System.String _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.String value);
        partial void OnUpdatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdatedOn
        {
            get
            {
                return _UpdatedOn;
            }
            set
            {
                OnUpdatedOnChanging(value);
                ReportPropertyChanging("UpdatedOn");
                _UpdatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedOn");
                OnUpdatedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdatedOn;
        partial void OnUpdatedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdatedOnChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjectSourceDb", "FK_Event_To_Feed", "ProjectSource")]
        public ProjectSource ProjectSource
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProjectSource>("ProjectSourceDb.FK_Event_To_Feed", "ProjectSource").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProjectSource>("ProjectSourceDb.FK_Event_To_Feed", "ProjectSource").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ProjectSource> ProjectSourceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProjectSource>("ProjectSourceDb.FK_Event_To_Feed", "ProjectSource");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ProjectSource>("ProjectSourceDb.FK_Event_To_Feed", "ProjectSource", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectSourceDb", Name="ProjectSourceType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProjectSourceType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProjectSourceType object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="assemblyName">Initial value of the AssemblyName property.</param>
        /// <param name="fullClassName">Initial value of the FullClassName property.</param>
        /// <param name="interval">Initial value of the Interval property.</param>
        /// <param name="nextRun">Initial value of the NextRun property.</param>
        /// <param name="enabled">Initial value of the Enabled property.</param>
        /// <param name="createdBy">Initial value of the CreatedBy property.</param>
        /// <param name="createdOn">Initial value of the CreatedOn property.</param>
        public static ProjectSourceType CreateProjectSourceType(global::System.Int32 id, global::System.String name, global::System.String assemblyName, global::System.String fullClassName, global::System.Int32 interval, global::System.DateTime nextRun, global::System.Boolean enabled, global::System.String createdBy, global::System.DateTime createdOn)
        {
            ProjectSourceType projectSourceType = new ProjectSourceType();
            projectSourceType.Id = id;
            projectSourceType.Name = name;
            projectSourceType.AssemblyName = assemblyName;
            projectSourceType.FullClassName = fullClassName;
            projectSourceType.Interval = interval;
            projectSourceType.NextRun = nextRun;
            projectSourceType.Enabled = enabled;
            projectSourceType.CreatedBy = createdBy;
            projectSourceType.CreatedOn = createdOn;
            return projectSourceType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AssemblyName
        {
            get
            {
                return _AssemblyName;
            }
            set
            {
                OnAssemblyNameChanging(value);
                ReportPropertyChanging("AssemblyName");
                _AssemblyName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AssemblyName");
                OnAssemblyNameChanged();
            }
        }
        private global::System.String _AssemblyName;
        partial void OnAssemblyNameChanging(global::System.String value);
        partial void OnAssemblyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FullClassName
        {
            get
            {
                return _FullClassName;
            }
            set
            {
                OnFullClassNameChanging(value);
                ReportPropertyChanging("FullClassName");
                _FullClassName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FullClassName");
                OnFullClassNameChanged();
            }
        }
        private global::System.String _FullClassName;
        partial void OnFullClassNameChanging(global::System.String value);
        partial void OnFullClassNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Interval
        {
            get
            {
                return _Interval;
            }
            set
            {
                OnIntervalChanging(value);
                ReportPropertyChanging("Interval");
                _Interval = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Interval");
                OnIntervalChanged();
            }
        }
        private global::System.Int32 _Interval;
        partial void OnIntervalChanging(global::System.Int32 value);
        partial void OnIntervalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastRun
        {
            get
            {
                return _LastRun;
            }
            set
            {
                OnLastRunChanging(value);
                ReportPropertyChanging("LastRun");
                _LastRun = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastRun");
                OnLastRunChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastRun;
        partial void OnLastRunChanging(Nullable<global::System.DateTime> value);
        partial void OnLastRunChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime NextRun
        {
            get
            {
                return _NextRun;
            }
            set
            {
                OnNextRunChanging(value);
                ReportPropertyChanging("NextRun");
                _NextRun = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NextRun");
                OnNextRunChanged();
            }
        }
        private global::System.DateTime _NextRun;
        partial void OnNextRunChanging(global::System.DateTime value);
        partial void OnNextRunChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Enabled
        {
            get
            {
                return _Enabled;
            }
            set
            {
                OnEnabledChanging(value);
                ReportPropertyChanging("Enabled");
                _Enabled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Enabled");
                OnEnabledChanged();
            }
        }
        private global::System.Boolean _Enabled;
        partial void OnEnabledChanging(global::System.Boolean value);
        partial void OnEnabledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private global::System.DateTime _CreatedOn;
        partial void OnCreatedOnChanging(global::System.DateTime value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private global::System.String _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.String value);
        partial void OnUpdatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdatedOn
        {
            get
            {
                return _UpdatedOn;
            }
            set
            {
                OnUpdatedOnChanging(value);
                ReportPropertyChanging("UpdatedOn");
                _UpdatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedOn");
                OnUpdatedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdatedOn;
        partial void OnUpdatedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdatedOnChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjectSourceDb", "FK_ProjectSource_To_ProjectSourceType", "ProjectSource")]
        public EntityCollection<ProjectSource> ProjectSources
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ProjectSource>("ProjectSourceDb.FK_ProjectSource_To_ProjectSourceType", "ProjectSource");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ProjectSource>("ProjectSourceDb.FK_ProjectSource_To_ProjectSourceType", "ProjectSource", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
